apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: feasample
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "sowmyavenky/feasample:1.0"
  imagePullPolicy: Always
  mainClass: com.gssystems.app.App
  mainApplicationFile: "local:///app/feasample-1.0-SNAPSHOT.jar"
  arguments:
    - /mnt/infile/
    - /mnt/outfile/
  sparkVersion: "3.1.3"
  restartPolicy:
    type: Never
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/www"
        type: Directory
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.3
    serviceAccount: spark
    volumeMounts:
      - name: "test-volume"
        mountPath: "/mnt"
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.1.3
    volumeMounts:
      - name: "test-volume"
        mountPath: "/mnt"
