---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/compoent: driver
    app.kubernetes.io/name: spark
    app.kubernetes.io/part-of: apache-spark
  name: spark
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/compoent: driver
    app.kubernetes.io/name: spark
    app.kubernetes.io/part-of: apache-spark
  name: spark
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - list
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/compoent: driver
    app.kubernetes.io/name: spark
    app.kubernetes.io/part-of: apache-spark
  name: spark
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spark
subjects:
- kind: ServiceAccount
  name: spark